### ISSUE TITLE
question: Using this framework in a WordPress plugin

### ISSUE THREAD

**Issue by atwellpub** [popphp/popphp-framework#2]
Hi!

I'm thinking of using this framework in a WordPress plugin. Could I selectively include file to support these fields, simply?

* text
* phone
* email
* text area
* checkbox
* radio
* dropdown
* country
* state/region

Also I am interested in localization, is there is an easy way to apply this? 

I am considering forking to implement localization, is the library pretty much complete and safe to fork?

Thank you for your time!

**Comment by nicksagona** [comment]
Hey - so if you use composer you could set the "require" to include `pop-form` and `pop-i18n` to take care of your form field and localization needs.
```
"require": {
        "popphp/pop-form": "^3.3.0",
        "popphp/pop-i18n": "^3.0.2"
}
```
Otherwise, you'd have to write some sort of manual autoloader to include all the required files in those components, which you could do with the `pop-loader` component.
